Repository ZB-Keyword/Keyword-FrontEnd, pull requests merged in 2024-01, with the labels that each got.

#11 Design/nav
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/CreateTodo/CreateTodoBody/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Nav/index.tsx
  src/components/common/Select/index.tsx
  src/pages/CreateTodo/index.tsx
  src/pages/CreateTodoPage/index.tsx
  src/pages/HomePage/HomeDetail/index.tsx
  src/pages/HomePage/index.tsx
Labels: 🎨 HTML&CSS

#13 Refactor: 라우팅
  src/App.tsx
  src/components/common/Header/index.tsx
  src/components/common/InnerCon/index.tsx
  src/components/common/LayoutWithHeader/index.tsx
  src/components/common/MainLayout/index.tsx
  src/hooks/query/search/useGetFriendsListQuery.tsx
  src/pages/HomePage/HomeDetail/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/search/index.tsx
Labels: 🔨Refactor

#14 Design/mypage
  src/components/common/TopTitle/index.tsx
  src/pages/MyPage/index.tsx
  tailwind.config.js
Labels: 🎨 HTML&CSS

#18 Feat/Design Schedule UI
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/CreateTodo/CreateTodoBody/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Date&TimePicker/Date/index.tsx
  src/components/common/Date&TimePicker/Time/index.tsx
  src/pages/todo/CreateTodoPage/index.tsx
Labels: ⭐️Feat, 🎨 HTML&CSS

#19 Feat: 프로필 사진 업데이트
  .eslintrc.cjs
  src/App.tsx
  src/components/Profile/PhotoEdit/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/InnerCon/index.tsx
  src/hooks/query/user/usePatchProfileImageQeury.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/user/handler.ts
  src/pages/mypage/ProfileEditPage/index.tsx
Labels: ⭐️Feat

#22 Feat/search-place
  index.html
  package-lock.json
  package.json
  src/components/common/Button/DefaultButton/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Map/index.tsx
  src/components/common/Map/react-kakao-maps.d.ts
  src/pages/todo/CreateTodoPage/index.tsx
Labels: ⭐️Feat, 🎨 HTML&CSS

#25 Fix: 모달 안닫히는 이슈
  src/components/Friends/RequestedFriends/ModalInReqOkOrNo/index.tsx
  src/components/common/Modal/index.tsx
  src/hooks/recoil/useModalState.tsx
Labels: 📍Fix

#31 #30 Feat: stomp 사용한 채팅
  package-lock.json
  package.json
  src/App.tsx
  src/components/Chatting/ChatRoom/ChatBody/index.tsx
  src/components/Chatting/ChatRoom/ChatFooter/index.tsx
  src/components/Chatting/ChatRoom/index.tsx
  src/pages/ChatPage/ChatDetail/index.tsx
  src/util/valid.ts
  vite.config.ts
Labels: ⭐️Feat

#52 Feat: 일정 수정 구현
  src/App.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/components/common/Input/index.tsx
  src/hooks/query/schedules/usePatchScheduleQuery.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/schedule/handler.ts
  src/pages/schedule/ScheduleEditPage/index.tsx
Labels: ⭐️Feat

#56 Fix: #55 데이터 없을경우 에러
  src/components/Schedule/MyschedulesList/index.tsx
  src/hooks/query/schedules/useGetSchedulesQuery.tsx
Labels: 📍Fix

#60 Feat/login continue
  package-lock.json
  package.json
  src/components/Profile/index.tsx
  src/hooks/query/auth/usePostLoginQuery.tsx
  src/hooks/recoil/useUserState.tsx
  src/main.tsx
  src/recoil/atoms/user/atom.ts
  src/types/auth/authDataType.ts
Labels: ⭐️Feat

#63 #62 Feat: 패스워드 변경 연동
  src/hooks/query/user/usePatchMyPasswordQuery.tsx
Labels: 🗄️API

#66 Api/profile image
  src/components/Friends/ RequestFriends/index.tsx
  src/components/Profile/PhotoEdit/index.tsx
  src/hooks/query/friends/useGetMyFriendsQuery.tsx
  src/hooks/recoil/useUserState.tsx
Labels: 🐞Bug, 🗄️API

#69 Fix] list no result
  src/App.tsx
  src/components/Chatting/ChatList/index.tsx
  src/components/Friends/ RequestFriends/index.tsx
  src/components/Friends/FriendsList/index.tsx
  src/components/Friends/MyFriends/index.tsx
  src/components/Friends/RequestedFriends/index.tsx
  src/constants/friends/index.ts
  src/hooks/query/chat/useGetChatListQuery.tsx
  src/hooks/query/friends/useGetMyFriendsQuery.tsx
  src/hooks/query/schedules/useGetSchedulesQuery.tsx
  src/hooks/query/search/useGetFriendsListQuery.tsx
  src/pages/ChatPage/index.tsx
Labels: 📍Fix

#71 Fix: 인피니트 스크롤 데이터 개수에 따라 비노출 처리
  src/App.tsx
  src/components/Chatting/ChatList/index.tsx
  src/components/Friends/ RequestFriends/index.tsx
  src/components/Friends/FriendsList/index.tsx
  src/components/Friends/MyFriends/index.tsx
  src/components/Friends/RequestedFriends/index.tsx
  src/components/Schedule/ModalInSelectedFriedns/index.tsx
  src/components/Schedule/MyschedulesList/index.tsx
  src/components/Search/SearchResultList/index.tsx
  src/hooks/useInfinite.tsx
  src/mocks/data.ts
  src/mocks/handlers/search/handler.ts
Labels: 📍Fix

#77 Fix profile edit user update
  src/apis/index.ts
  src/components/Friends/FriendsItem/index.tsx
  src/components/Profile/PhotoEdit/index.tsx
  src/components/Profile/index.tsx
  src/hooks/query/user/useGetProfileQuery.tsx
  src/hooks/query/user/usePatchProfileImageQeury.tsx
Labels: 📍Fix

#78 Api/friend request
  src/components/Friends/FriendsItem/index.tsx
  src/components/Friends/RequestedFriends/ModalInReqOkOrNo/index.tsx
  src/constants/friends/index.ts
  src/hooks/query/auth/usePostLoginQuery.tsx
  src/hooks/query/friends/useDeleteMyFriendQuery.tsx
  src/hooks/query/friends/usePatchMyFriendReqQuery.tsx
  src/hooks/query/friends/usePostFriendAddQuery.tsx
  src/mocks/handlers/friends/handler.ts
  src/recoil/atoms/modal/types.ts
  src/types/friend/friendsDataType.ts
Labels: 📍Fix

#81 Feat/account close
  src/apis/index.ts
  src/components/AuthLayout/index.tsx
  src/components/Mypage/AccountClose/index.tsx
  src/components/common/InnerCon/index.tsx
  src/constants/auth/index.ts
  src/hooks/query/auth/usePostLoginQuery.tsx
  src/hooks/query/user/useDeleteAccountQuery.tsx
  src/pages/mypage/index.tsx
  src/recoil/atoms/user/atom.ts
Labels: ⭐️Feat, 🗄️API

#84 #83 Feat: 로딩팝업 생성
  src/components/common/Loading/LoadingPopup/index.tsx
  src/hooks/query/auth/usePostLoginQuery.tsx
  src/pages/auth/LoginPage/index.tsx
Labels: ⭐️Feat, 📍Fix

#85 Api/schedule create
  src/components/Schedule/ModalInSelectedFriedns/index.tsx
  src/components/Schedule/MyschedulesList/MySchdulesItem/index.tsx
  src/components/Schedule/ScheduleCreate/ScheduleAddr/index.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/components/common/Select/SelectOption/index.tsx
  src/hooks/query/chat/usePostChatRoomQuery.tsx
  src/hooks/query/schedules/useDeleteScheduleQuery.tsx
  src/hooks/query/schedules/usePostSchedulesQuery.tsx
  src/hooks/query/user/useGetProfileQuery.tsx
  src/hooks/recoil/useModalState.tsx
  src/index.css
  src/pages/schedule/ScheduleDetailPage/index.tsx
  src/types/auth/authDataType.ts
  src/types/schedule/scheduleDataType.ts
Labels: 📍Fix, 🗄️API

#87 Api/schedule detail
  index.html
  src/components/Friends/RequestFriends/index.tsx
  src/components/KakaoMap/index.tsx
  src/components/Schedule/ModalAttendingFriends/index.tsx
  src/components/Schedule/ModalInSelectedFriedns/index.tsx
  src/components/Schedule/MyschedulesList/MySchdulesItem/index.tsx
  src/components/Schedule/ScheduleCreate/ScheduleFriends/index.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/components/common/Button/WideButton/index.tsx
  src/components/common/InnerCon/index.tsx
  src/components/common/TopTitle/index.tsx
  src/hooks/query/schedules/useGetScheduleDetailQuery.tsx
  src/hooks/recoil/useModalState.tsx
  src/pages/mypage/RequestdFriendsPage/index.tsx
  src/pages/schedule/ScheduleDetailPage/index.tsx
  src/types/schedule/scheduleDataType.ts
  vercel.json
Labels: 📍Fix, 🗄️API, 🎨 HTML&CSS

#94 Api/schedule edit
  src/apis/index.ts
  src/components/Schedule/ModalAttendingFriends/index.tsx
  src/components/Schedule/ScheduleCreate/ScheduleFriends/index.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/hooks/query/schedules/usePatchScheduleQuery.tsx
  src/hooks/query/schedules/usePostSchedulesQuery.tsx
  src/pages/schedule/ScheduleDetailPage/index.tsx
  src/pages/schedule/ScheduleEditPage/index.tsx
  src/recoil/atoms/schedule/atom.ts
  src/types/schedule/scheduleDataType.ts
Labels: ⭐️Feat, 🗄️API

#95 #90 Add: 리스트에 장소가 추가된 UI로 수정
  src/components/Schedule/MyschedulesList/MySchdulesItem/index.tsx
  src/components/Schedule/MyschedulesList/index.tsx
Labels: ⭐️Feat

#96 #89 Add: 파비콘/타이틀 설정
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  src/App.tsx
  src/components/SEO/indext.tsx
  src/main.tsx
  src/pages/ChatPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/auth/JoinPage/index.tsx
  src/pages/auth/LoginPage/index.tsx
  src/pages/mypage/index.tsx
  src/pages/schedule/ScheduleDetailPage/index.tsx
  src/pages/search/index.tsx
Labels: ⭐️Feat

#98 Refactor lazy loading
  package-lock.json
  package.json
  src/App.tsx
  src/components/Chatting/ChatRoom/ChatFooter/index.tsx
  src/components/Chatting/ChatRoom/index.tsx
  src/components/Profile/PhotoEdit/index.tsx
  src/components/Profile/index.tsx
  src/components/SEO/index.tsx
  src/components/Schedule/ModalAttendingFriends/index.tsx
  src/components/Schedule/MyschedulesList/MySchdulesItem/index.tsx
  src/components/Schedule/ScheduleCreate/ScheduleFriends/index.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/components/Search/SearchBar/index.tsx
  src/components/common/Alarm/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/DateTimePicker/Date/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Nav/index.tsx
  src/components/common/Naver/index.tsx
  src/components/common/TopTitle/index.tsx
  src/hooks/recoil/useScheduleState.tsx
  src/pages/ChatPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/auth/JoinPage/index.tsx
  src/pages/auth/LoginPage/index.tsx
  src/pages/mypage/index.tsx
  src/pages/schedule/ScheduleDetailPage/index.tsx
  src/pages/search/index.tsx
  src/recoil/atoms/user/atom.ts
  src/types/user/userDataType.ts
Labels: 🔨Refactor

#99 Bug/infinite scroll
  src/App.tsx
  src/components/Chatting/ChatList/index.tsx
  src/components/Friends/FriendsItem/index.tsx
  src/components/Friends/FriendsList/index.tsx
  src/components/Schedule/MyschedulesList/index.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/hooks/query/chat/useGetChatListQuery.tsx
  src/hooks/query/friends/useGetMyFriendsQuery.tsx
  src/hooks/query/schedules/useGetSchedulesQuery.tsx
  src/hooks/query/schedules/usePatchScheduleQuery.tsx
  src/hooks/query/search/useGetFriendsListQuery.tsx
  src/hooks/query/user/useGetProfileQuery.tsx
  src/hooks/query/user/usePatchProfileImageQeury.tsx
  src/hooks/useInfinite.tsx
  src/types/pageable.ts
Labels: 🐞Bug

#101 #100 Feat: 네이버 로그인 연동
  public/images/ico-naver.svg
  src/App.tsx
  src/components/common/Loading/LoadingPopup/index.tsx
  src/components/common/Naver/index.tsx
  src/hooks/query/auth/usePostLoginQuery.tsx
  src/pages/AlarmPage/index.tsx
  src/pages/auth/NaverLoginPage/index.tsx
  src/pages/auth/NotLoginPage/index.tsx
  tailwind.config.js
Labels: ⭐️Feat

#105 #104 Feat: 일정목록 스켈레톤 추가
  src/components/Friends/FriendsItem/index.tsx
  src/components/Schedule/MyschedulesList/index.tsx
  src/components/common/Skeleton/ItemList/index.tsx
  src/pages/HomePage/index.tsx
Labels: ⭐️Feat

#107 Feat/chat connect
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/Chatting/ChatList/Chatitem/indext.tsx
  src/components/Chatting/ChatRoom/ChatList/index.tsx
  src/components/Chatting/ChatRoom/index.tsx
  src/components/Schedule/ScheduleCreate/index.tsx
  src/components/common/Modal/index.tsx
  src/constants/chat/index.ts
  src/hooks/query/chat/useGetChatRoomQuery.tsx
  src/pages/ChatPage/ChatDetail/index.tsx
  src/recoil/atoms/chat/atom.ts
  src/types/chatting/chatDataType.ts
  src/util/ date.ts
  vite.config.ts
Labels: ⭐️Feat
